apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - image: jmezna/javasi-customers:0.05
        name: customer
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: openshift
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-customers:5432/customer
          - name: KUMULUZEE_HEALTH_CHECKS_DATASOURCEHEALTHCHECK_CONNECTIONURL
            value: jdbc:postgresql://postgres-customers:5432/customer
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: dbuser
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
