kumuluzee:
  name: customer-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/customer
      username: dbuser
      password: postgres
      max-pool-size: 20
  cors-filter:
        servlet:
          allow-origin: "*"
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
rest-properties:
  external-services:
    order-service:
      enabled: true
