kumuluzee:
  name: customer-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/customer
      username: dbuser
      password: postgres
      max-pool-size: 20
  cors-filter:
        servlet:
          allow-origin: "*"
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  logs:
      config-file:
        '<?xml version="1.0" encoding="UTF-8"?>
         <Configuration name="tutorial-logging">
             <Appenders>
                 <Console name="console" target="SYSTEM_OUT">
                     <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                 </Console>

                 <!-- A socket definition for sending logs into Logstash using TCP and JSON format.-->
                 <!--<Socket name="logstash" host="localhost" port="5043" protocol="tcp">
                     <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                 </Socket>-->

             </Appenders>
             <Loggers>
                 <!-- Default logger -->
                 <Root level="info">
                     <AppenderRef ref="console"/>
                     <!--<AppenderRef ref="logstash"/>-->
                 </Root>
             </Loggers>
         </Configuration>'
rest-properties:
  external-services:
    order-service:
      enabled: true
